### ISSUE TITLE
contributing wiki page

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#103]
Need to write up a wiki page on the workflow for contributing.
I consider this marketing since it attracts developers who want to help.

**Comment by omenking** [comment]
I think this is good enough.

@Skytrias 

https://github.com/omenking/swap-n-pop/wiki/Contributing-Guide

**Comment by omenking** [comment]
@RauliL  @conormackeigan 

If I can get suggestions or improvements to the contributing Guide

**Comment by Skytrias** [comment]
I think the guide is pretty solid, maybe a small video could show an example where i would add a feature to the game. But anyone knowing a bit about git etc wouldnt have a problem starting out.
