### ISSUE TITLE
Round Counter sprite/concept

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#106]
We should probably come up with something other than stars.

![screen shot 2017-11-28 at 11 16 44 pm](https://user-images.githubusercontent.com/7776/33357754-45a2e76c-d492-11e7-8ba6-24d074796713.png)

Consult @Wish-Star for an idea other than stars.

I think we can go beyond best 2 out of 3 which is what is current.
PPL did best 4 out of 5
I think we can go as far as 6 out of 7.

We can move the round counter anywhere we like. We don't have to keep it in center if you have some better idea.

- [ ] concept other than star, or at least divergent enough from TA
- [ ] system that supports more that 2 out of 3

**Comment by Skytrias** [comment]
moved to meistertask
