### ISSUE TITLE
bauble/card sprite

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#111]
We need high resolution version of bauble
Also consider maybe updating the sprites as well

Here are current sprite files

![bauble_num_small](https://user-images.githubusercontent.com/7776/33359273-e7b08100-d49b-11e7-9c35-9435f72fe17e.png)
![bauble_num](https://user-images.githubusercontent.com/7776/33359274-e7bd3ac6-d49b-11e7-8e17-aa214fb38031.png)
![bauble_times](https://user-images.githubusercontent.com/7776/33359275-e7c893b2-d49b-11e7-8a56-9f0414f66be5.png)
![bauble](https://user-images.githubusercontent.com/7776/33359276-e7d51f38-d49b-11e7-9d4c-bf2c05e93436.png)

**Comment by omenking** [comment]
I assigned @Wish-Star if she has any input to assist Neweegee with ideas.

**Comment by Skytrias** [comment]
moved to meistertask
