### ISSUE TITLE
4combo garbage should never spawn in middle

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#151]
Reported by @jon12156 
4combo garbage blocks should spawn against the edges, using columns 1-3 or 4-6, never in the middle anywhere.

**Comment by omenking** [comment]
When I had set up how they alternate I kind of just guessed.

```ts
    // 0 1 2 3 4 5
    this.alternate = [
      {index: 0, frame: [0,1,2,3,4,5]}, // 1 garbage wide
      {index: 0, frame: [0,4,2]},       // 2 garbage wide
      {index: 0, frame: [0,3,1,2]},     // 3 garbage wide
      {index: 0, frame: [0,2]},         // 4 garbage wide
      {index: 0, frame: [0,1]},         // 5 garbage wide
      {index: 0, frame: [0]}            // 6 garbage wide
    ]
```

**Comment by omenking** [comment]
@jon12156 if you know the other cases for other garbage sizes would like to know

**Comment by omenking** [comment]
The 3wides are special, the others spawn in every index possible for them, in order from left to right, and then they loop back to the left position(edited)
(Not considering garbage less than 3 wide)

**Comment by jon12156** [comment]
this is fixed, isn't it?

**Comment by Skytrias** [comment]
yes should be fixed, otherwhise we'll reopen this
