### ISSUE TITLE
mock * as from

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#152]
This is what I'm mocking
```ts
import * as electron from 'electron'
```

Here's my mock
```ts
const sinon = require('sinon')

const ElectronMock = {
  app: null,
  remote: { app: null},
  ipc: {
    on: sinon.stub()
  },
  ipcRenderer: {
    on: sinon.stub()
  }
}

export default ElectronMock
```

Won't work since I can't have a default. Unsure how I replicate export so its

```ts
import * as electron from 'electron'
```

@RauliL  If we can get some of your typescript magic here

**Comment by RauliL** [comment]
That import looks weird as well.

**Comment by omenking** [comment]
Let me describe further. If you were to console.log out electron:
```
import * as electron from 'electron'
console.log('electron',electron)
```

You'll get back a json  object eg . `{ app: .. , remote ... , ipcRenderer }`

So when mocking we need to preserve this structure.
I would have thought this would work:

```
export function app() {}
export function remote() {}
```

or this

```
export { app: .. , remote ... , ipcRenderer }
```

Though my console.log either returns it wrapped in `electron` or an empty json object `{}`, or wrapped in fuctions.
