### ISSUE TITLE
Array out of bounds error when chaining a combo

### ISSUE THREAD

**Issue by conormackeigan** [omenking/swap-n-pop#157]
Got a x2 chain, 5-combo and the game crashed on the last pop. Seems like renderer.js is trying to play a pop SFX that is out of bounds. Not sure if this was present before the recent refactors/ports.
![5combo-2chain-crash](https://user-images.githubusercontent.com/15354263/33792859-100660ae-dc79-11e7-8b68-2fbcca15f593.png)

**Comment by omenking** [comment]
Ah yes the pop count going incorrect.
This has been here for a while.
Its an easy fix
