### ISSUE TITLE
controller acceleration framedata

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#164]
Currently before the cursor moves while holding its set to 15 frames and then the cursor moves per frame.

I hear it's different between snes and n64, and panel attack.

@jon12156 Should we just make a new hardcoded standard. or is this something where we want to make it custom, and have presets for different versions.

Is there anything beyond the x frame delay that needs to be done to modularize this?
Once it starts moving is it always 1 frame and move or does it accelerate differently?

**Comment by jon12156** [comment]
I have not checked this yet, but for now, I would hard code it at 15 frames.

I Imagine there is nothing else to do to modularize it.  I expect it to move 1 space per frame after the delay.
If we do decide to make it user adjustable, we'd better be sure the other client or server (or replay system) knows what their arrow press repeat delay was.

**Comment by Skytrias** [comment]
when i looked at the frame data i found out the cursor starts moving again after 10 frames. This seems really low tho so confirmation would be good. But we could try out 10 frames for now
