### ISSUE TITLE
fade in and out to black for transitions

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#174]
To improve the overall experience, fade in or out from black would looks nice.
Tetris Attack does this.

**Comment by Skytrias** [comment]
overall transition from black or transition from black only above the playfield?

**Comment by omenking** [comment]
The who screen would fade to black.
So you could just have a big black shape cover the entire screen and tween its opacity.

When there is a transition should likely be between states. so going from Menu to ModeVs etc...

**Comment by Skytrias** [comment]
shouold be easy with phaser tweens if it should do some effects like sizing, alpha, coloring etc
