### ISSUE TITLE
Swaps are not interruptable

### ISSUE THREAD

**Issue by conormackeigan** [omenking/swap-n-pop#219]
Classic games allow a swap to be interrupted with a new swap, which forces the old swap to finish immediately before starting the new swap.

**Comment by conormackeigan** [comment]
basically fully functional, though there are two slight differences from Tetris Attack:

When a swap is interrupted with the same swap, they smoothly maintain their positions (counter) in the swap, and begin reversing. In Swap'N'Pop, they are forced to their swap-finish position, then complete a full swap from there.

eg:
![reswap_unsmooth](https://user-images.githubusercontent.com/15354263/34458458-d176d42e-eda1-11e7-9c02-4bdd4142cd81.gif)

vs

![reswap_smooth](https://user-images.githubusercontent.com/15354263/34458460-e7d37fba-eda1-11e7-9fec-3e389c9a93fb.gif)


Additionally, when only one panel of an old swap is being interrupted, in Tetris Attack it **does** snap to its finished position immediately, whereas in Swap'N'Pop, it continues smoothly towards its destination.

eg:
![swap_interrupt_snp](https://user-images.githubusercontent.com/15354263/34458465-121d46d4-eda2-11e7-815e-a30a02331618.gif)

vs

![swap_interrupt_ta](https://user-images.githubusercontent.com/15354263/34458466-1918b9fa-eda2-11e7-8814-3419470f6eeb.gif)

**Comment by Skytrias** [comment]
nice work ill close this since it works, i think you should upload the gifs to sites like imgur etc since they dont run good on github
