### ISSUE TITLE
Panels turning invisible for a frame under some conditions

### ISSUE THREAD

**Issue by conormackeigan** [omenking/swap-n-pop#226]
Easiest to replicate with a chain:
![2017-12-28_22-01-08](https://user-images.githubusercontent.com/15354263/34428456-f121ae62-ec1a-11e7-80c2-db67fa30dafd.gif)

**Comment by omenking** [comment]
https://i.imgur.com/mSIg5g3.gif

**Comment by Skytrias** [comment]
has this bug been fixed yet? havent been up to date
