### ISSUE TITLE
should hook up sliders to change volumn on sfx and music 

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#24]
These sliders are for show and currently do not work. They need to be hooked up.
All of our sound should be handled by `core/sounds`. Not everything has been centralized into 
class so you may need to move what you can find.'

![screen shot 2017-09-18 at 3 44 37 pm](https://user-images.githubusercontent.com/7776/30561208-4b28295a-9c88-11e7-9635-d346397af013.png)

**Comment by Skytrias** [comment]
The sliders now properly work even while sounds are running.

The only issue im thinking off now is that the values of each slider arent saved from last startup - and also dont effect the sfx & msx on startup -> just once they are moved.

**Comment by Skytrias** [comment]
values are now saved
