### ISSUE TITLE
Concurrent disjointed chains do not stack

### ISSUE THREAD

**Issue by conormackeigan** [omenking/swap-n-pop#246]
When achieving a chain while another chain is still active, the new chain should stack with the old chain's value.

Bad:
![chain_stack_snp](https://user-images.githubusercontent.com/15354263/34458546-6b089cf6-eda4-11e7-9a35-b29940f79557.gif)

Good:
![chain_stack_ta](https://user-images.githubusercontent.com/15354263/34458547-754c40e6-eda4-11e7-98fc-a09db3e24222.gif)

**Comment by omenking** [comment]
So as I understand it. If you have a chain in process, anything else should always stack on the current chain

**Comment by conormackeigan** [comment]
Correct. That itself shouldn't be too difficult with our current model, but it raises the question of how to detect when a chain has ended. Is there any way to store a list of panel references/pointers in ts/js?
