### ISSUE TITLE
should have a mute toggle/hotkey

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#25]
We need a mute checkbox that mutes all sound.

![screen shot 2017-09-18 at 3 44 37 pm](https://user-images.githubusercontent.com/7776/30561308-9304d99e-9c88-11e7-85c6-24d45ef7ab2e.png)

We also need a hotkey for toggling mute

![screen shot 2017-09-18 at 3 47 07 pm](https://user-images.githubusercontent.com/7776/30561335-a50ebb78-9c88-11e7-827f-ca2a441fabb4.png)

**Comment by Skytrias** [comment]
Just implemented the mute checkbox. Same with the slider values - these values arent saved and also dont apply on startup.

![grafik](https://user-images.githubusercontent.com/22886746/33341015-e78a670e-d47d-11e7-8313-12567db75e42.png)

**Comment by Skytrias** [comment]
values are now saved
