### ISSUE TITLE
toggle to fullscreen

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#26]
We need a hotkey for toggling to fullscreen.
I already added an event for this in main.js:

```js
ipc.on('fullscreen', (event,name) => {
  win.setFullScreen(!win.isFullScreen())
})
```
![screen shot 2017-09-18 at 3 47 07 pm](https://user-images.githubusercontent.com/7776/30561375-cd69434a-9c88-11e7-8253-dbb35d421a7f.png)

It would have been easy but I came at a crossroads because we currently check on keyboard inputs three ways.

`settings.js` just watches on document
`index.js` uses phaser
chrome itself watches keypresses someway.

This problem could be negated if we merge `settings.js` and `index.js` into one interface.
We might end up doing this because we need to create our own UI since the native UI looks ugly and electron apps tend to do it all in one window since its only way it looks good.

**Comment by Skytrias** [comment]
toggling fullscreen is possible now. only thing would be settings its key customizable?

**Comment by omenking** [comment]
That is correct

**Comment by omenking** [comment]
![screen shot 2018-01-22 at 9 22 40 pm](https://user-images.githubusercontent.com/7776/35254938-6f8e4118-ffba-11e7-93c8-e63c4a43a18a.png)
