### ISSUE TITLE
Force-push stack buffered from previous game

### ISSUE THREAD

**Issue by conormackeigan** [omenking/swap-n-pop#263]
Hold shoulder button to force raise until dead, quit out, start a new game, the stack will automatically rise one row.

**Comment by Skytrias** [comment]
this is still a big issue, why did you remove it from the milestone @omenking ?

**Comment by Skytrias** [comment]
i knew of this bug but cant recreate it anymore, has this been fixed by someone?

**Comment by omenking** [comment]
fixed it
