### ISSUE TITLE
When there is a gameover it should animate a brick wall rolling over the display field

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#29]
When you get a game over the game will shake. Maybe before or after the brick wall rolls. Then it display a game over for the loser. We should create a new component for this. eg. `ComponentWall`

**Comment by Skytrias** [comment]
Think you implemented this already right? Or ist it still unfinished

**Comment by omenking** [comment]
The brick wall currently rolls up. It also needs to roll down.
Its just a matter of counting the frame data

So here I had manually recorded how many pixels the wall moved for roll up, and the same would need to be done for roll down
```js
  WALL_ROLLUP: [
    0,1,0,1,0,1,0,2,0,2,0,
    2,0,3,3,0,3,0,4,4,0,
    4,0,5,5,0,5,0,6,0,6,
    0,7,7,0,7,0,0,8,0,0,
    8,0,0,8,0,9,9,0,16,32,
    48,64,80,96,112,128,144,160,176,192,
    192,188,185,185,188,192,192,189,187,187,
    189,192,192,190,189,189,190,192,192,190,
    192,190,192,191,192,191,192,191,192
  ],
```
