### ISSUE TITLE
Comment out modes that do not work from the menu yet.

### ISSUE THREAD

**Issue by Skytrias** [omenking/swap-n-pop#312]
Once a menu item is selected and doesnt lead to anything it should atleast show a text on what the mode is supposed to be in the future and say it isnt finished yet.

**Comment by omenking** [comment]
The menu is going to get reorganized with the new design and for modes that don't work such as `Challenges` we can just comment them out for the time being.

**Comment by omenking** [comment]
![screen shot 2018-02-08 at 9 07 56 pm](https://user-images.githubusercontent.com/7776/36008200-2f31e130-0d14-11e8-98cb-45f6439c226b.png)
