### ISSUE TITLE
Should not be able to pause game if game is in gameover state

### ISSUE THREAD

**Issue by Skytrias** [omenking/swap-n-pop#328]
![2018-02-07_21-55-17](https://user-images.githubusercontent.com/22886746/35941183-b47ba948-0c51-11e8-9d53-3f2960449719.gif)
A bug i noticed when the game was finished and all panels were dead, once you would pause they would simply look normal again. When resuming the have the dead face again. Probably some rendering bug.

**Comment by omenking** [comment]
I wonder if its because the state of the game changes from gameover to pause for the moment it is paused.

```
    } else if (this.dead === true && this.playfield.stage.state === 'gameover'){
      this.frame = assets.spritesheets.panels.animations.dead
```

**Comment by omenking** [comment]
I guess a better question would be should you be allowed to pause a game during gameover state?
I would think not since there is not really anything to pause
