### ISSUE TITLE
Stop Timer counting when the game is paused

### ISSUE THREAD

**Issue by Skytrias** [omenking/swap-n-pop#33]
First try at Issues im sorry in advance ^^.

I'll try to fix it myself since its a rather easy fix but i just want to know if these rather simple issues should also be posted or not.

When the pause is pressed and the game doesnt move the Timer should just stop counting, so an if enhancement would only be necessary.

This might be a different topic when it comes to Multiplayer tho. If one player pauses, should the other player's Screen be paused either? Sure but will he have control over closing the pause screen or will he just have to wait. More complicated than I thought

**Comment by omenking** [comment]
I think in a ranked online matched pausing should not be possible so control is not a concern.
In the case of unranked online matches I think we should deviate from TA and allow both players to move the pause the screen.

Currently there are two pause screens. One create for each playfield. We should really only have one which should be created by the stage which is `mode_vs`.

**Comment by omenking** [comment]
Also Timer is suppose to be added to snapshots. You might want to try this. Its very easy.
You just need to create a `load` and `snap` for the timer. Then you simply need to add them to the `snapshots` controller.

**Comment by omenking** [comment]
-[] instead of creating two pause menus create one shared on in `mode_vs`
-[] both players in a unranked game should be able to move the pause screen
-[] timer should pause when the pause screen is active
-[] timer should be added to snapshots so that bother players timer's stay in sync

**Comment by Skytrias** [comment]
added everything to my branch. Dont know how to test the snap case but technically everything should work out properly.
