### ISSUE TITLE
pausing and playing game causes music to stack

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#334]
If I pause, play, pause play. I will hear multiple versions of music track playing at the same time.

**Comment by omenking** [comment]
While playing it hasn't been occurring so uncertain if this was just the state of when I was playing.
I will test it more later today.

**Comment by Skytrias** [comment]
oh i thought this happened after my audio changes. yea no this happened before the changes i made and has been fixed already

**Comment by omenking** [comment]
excellent to here
