### ISSUE TITLE
should not be able to redact a swap over empty space

### ISSUE THREAD

**Issue by jon12156** [omenking/swap-n-pop#340]
![snpstealthoverpit](https://user-images.githubusercontent.com/32025765/36066107-756dcf8a-0e61-11e8-88ae-161d1f512711.gif)

should not be able to redact a swap over empty space or continue to swap it again in either direction.  Also, it's generating that ghost blue block that shouldn't exist.

**Comment by Skytrias** [comment]
cant recreate this consistantly to know where the problem arises, specs also behave weirdly with swapping. this is possibly an issue with being able to swap blocks after each other which prophet implemented a while ago, so maybe he understands why this happens

**Comment by omenking** [comment]
a panel has a kind and null will translate to 0.
So its likely the phantom panel is actually a null panel.
In this case there is an issue with the `render_visible' function in the panel.

For the case of the swapping over an empty space, it appears the panel is in a hang or fall state while swapping. I think prophet had code that allowed you swap falling panels which made sense in another edge case but might not be possible in this case.

**Comment by Skytrias** [comment]
okay so after some digging and spec testing it seems like its a result of swappable() allowing to much or just needs to be more strictful about what can be swapped. ill experiment a bit

**Comment by Skytrias** [comment]
some of the issues were possibly done through short circuiting, but one of errors was that a falling panel could be switched, but it shouldnt be able to be switched if the panel that it will be switched to isnt a real panel, so a panel.kind !== null. this works nicely now with specs

**Comment by Skytrias** [comment]
ok last error is fixed the same way now, blocks should be able to break up switching but not be able to do that when the panel to be swapped is empty, will put in specs to show this
