### ISSUE TITLE
When a player wins a round in ModeVs they the should be awarded a star

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#35]
When a player wins a round they the should be awarded a star

- [x] should count rounds when people win or lose
- [ ] should be flexible to support any best x out of y

The sprite and concept work is being worked out. Currently the TA artwork is implemented so functionality should not be impeded.

### Related Ticket
#106 Round Counter sprite/concept

**Comment by omenking** [comment]
- [ ] add animation, sprites, and correctly place it position
- [ ] should have variable for determining `rounds_won`
- [ ] get exact frame data
- [ ] should animate particles when added
- [ ] should be part of snapshop

**Comment by Skytrias** [comment]
can you elaborate on should be flexible to support any best x out of y?

**Comment by omenking** [comment]
So to get to this ticket I made it so the wall will roll up and then down, and as it rolls down it will reset the panels. So its a smooth transition
