### ISSUE TITLE
Florice's character concept

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#72]
### Tasks
- [x] Concept Sketch
![unknown](https://user-images.githubusercontent.com/7776/33355802-06d1c5ea-d487-11e7-8d9b-20e2a87e37a2.png)

- [ ] Colour Palette
- [x] Character Name
Her name if **Florice** and she is a **rabbit**
- [ ] Character Personality
- [ ] Determine General Setting
- [ ] Determine General Backstory

**Comment by Skytrias** [comment]
moved to meistertask
