### ISSUE TITLE
Zephyr's character concept 

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#73]
### Tasks
- [x] Concept Sketch
Consider these concepts it no reflective of correct colour pallete
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3336363737323833373139303436373538352f3336363832323336373630303537343436342f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/7776/33355941-bb44033a-d487-11e7-90ea-3dfdd37680ae.png)
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3336363737323833373139303436373538352f3336373435373333343235363939323235362f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/7776/33355946-beb65946-d487-11e7-8d59-ab6c735b4456.png)

- [x] Colour Palette
This is final colour palette
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3336363737323833373139303436373538352f3336373738323237383239313635323630382f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/7776/33355923-96914386-d487-11e7-9f8a-f565e9a1a37a.png)

- [x] Character Name
His name is **Zephyr** and he is a **dragon**

- [x] Character Personality
Zephyr is generally a nice kid. He loves to help people whenever he can, and loves making new friends. However, he can be a bit blunt sometimes, and is quite rash with his actions.
Oh, he can't fly either, which is why he rides around on a cloud. He's pretty embarrassed by this.

- [x] Determine General Setting
Sky Village, which is just a village on a high mountain.
- [ ] Determine General Backstory
W.I.P

**Comment by Skytrias** [comment]
moved to meistertask
