### ISSUE TITLE
Kindle's character concept

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#74]
### Tasks
- [x] Concept Sketch
![grafik](https://user-images.githubusercontent.com/22886746/33520098-996a4370-d7b4-11e7-9c2e-cba0d7470db9.png)
- [x] Colour Palette
Her color palette is completed for now. It may be changed in the future.
- [x] Character Name
Her name is **Kindle** and she is a **monkey**
- [x] Character Personality
Serious
Logical
Decisive
- [x] Determine General Setting
Charred Ruins
- [ ] Determine General Backstory
W.I.P

**Comment by Skytrias** [comment]
moved to meistertask
