### ISSUE TITLE
add popping animation to clearing panels

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#9]
Sorry for the ugly screengrab just needed an example:
![screen shot 2017-09-18 at 3 56 02 pm](https://user-images.githubusercontent.com/7776/30561713-e45f7b04-9c89-11e7-823e-315b57cccf14.png)

When a panel pops, it has 4 particles that animate. That is what I'm describing.

**Comment by Skytrias** [comment]
Panel clear animations are fully in right now. 
The way they animate is determined by the set TIME_PARTICLE amount and the Sprite's amount of horizontal frames. 
Different movement like rotation can be easily added in the update callback of the PanelParticle
